---
- name: Install Clickhouse
  hosts: clickhouse
  handlers:
    - name: Start clickhouse service
      become: true
      ansible.builtin.service:
        name: clickhouse-server
        state: restarted
  tasks:
    - name: Get clickhouse distrib
      ansible.builtin.get_url:
        url: "https://packages.clickhouse.com/deb/pool/main/c/{{ item }}/{{ item }}_{{ clickhouse_version }}_amd64.deb"
        dest: "./{{ item }}_{{ clickhouse_version }}_amd64.deb"
        mode: "0755"
      with_items: "{{ clickhouse_packages }}"
    - name: Install clickhouse packages
      ansible.builtin.apt:
        deb: "./{{ item }}"
      with_items:
        - "clickhouse-common-static_{{ clickhouse_version }}_amd64.deb"
        - "clickhouse-client_{{ clickhouse_version }}_amd64.deb"
        - "clickhouse-server_{{ clickhouse_version }}_amd64.deb"
    - name: Ensure ClickHouse server is running
      ansible.builtin.service:
        name: clickhouse-server
        state: started
    - name: Flush handlers
      ansible.builtin.meta: flush_handlers
    - name: Create database
      ansible.builtin.command: "clickhouse-client -q 'create database logs;'"
      register: create_db
      failed_when: create_db.rc != 0 and create_db.rc != 82
      changed_when: create_db.rc == 0

- name: Install Vector
  hosts: vector
  become: true
  handlers:
    - name: Restart Vector
      ansible.builtin.systemd:
        name: vector
        state: restarted

  tasks:
    - name: Loading Vector
      ansible.builtin.get_url:
        url: "https://packages.timber.io/vector/0.43.0/vector-0.43.0-x86_64-unknown-linux-gnu.tar.gz"
        dest: "/tmp/vector-0.43.0-x86_64-unknown-linux-gnu.tar.gz"
        mode: "0755"

    - name: Unboxing Vector
      ansible.builtin.unarchive:
        src: "/tmp/vector-0.43.0-x86_64-unknown-linux-gnu.tar.gz"
        dest: "/opt/"
        remote_src: true

    - name: Create configuration
      ansible.builtin.file:
        path: "/etc/vector/"
        state: directory
        recurse: true
        owner: root
        group: root
        mode: "0755"

    - name: Copy template
      ansible.builtin.template:
        src: "./template/vector_config.yml.j2"
        dest: "/etc/vector/vector.conf"
        owner: root
        group: root
        mode: "0644"
      notify: Restart Vector

    - name: Configure Vector
      ansible.builtin.command: /opt/vector-x86_64-unknown-linux-gnu/bin/vector --config /etc/vector/vector.conf
      async: 30
      poll: 0
      notify: Restart Vector

    - name: Ensure Vector service is running
      ansible.builtin.systemd:
        name: vector
        state: started
        enabled: true
